"""
Sentinel Backend — FastAPI Application Entry Point

This is the foundation-stage backend for Sentinel.

Currently implemented:
  GET /          — Service identifier
  GET /health    — Health probe

NOT YET implemented (see docs/architecture/api-contract.md for planned endpoints):
  /cases         — Case management
  /evidence      — Evidence ingestion and integrity
  /analysis      — AI analysis job orchestration
  /timeline      — Unified event timeline
  /graph         — Evidence relationship graph
  /anomalies     — Anomaly records

To run locally:
  pip install -r requirements.txt
  uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

API documentation (auto-generated by FastAPI):
  http://localhost:8000/docs     (Swagger UI)
  http://localhost:8000/redoc    (ReDoc)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# ---------------------------------------------------------------------------
# Application instance
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Sentinel API",
    description=(
        "Sentinel is a local-first multimodal AI system for insider-threat "
        "investigation assistance. This API is in the foundation stage; most "
        "endpoints are planned and not yet implemented."
    ),
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ---------------------------------------------------------------------------
# CORS
# In development, allow the Vite frontend origin.
# Restrict in production to the actual frontend host.
# ---------------------------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite dev server default
        "http://localhost:3000",   # Alternative dev port
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Root endpoint
# ---------------------------------------------------------------------------


@app.get("/", tags=["Status"])
async def root() -> dict:
    """Return a basic service identifier."""
    return {
        "service": "Sentinel API",
        "status": "running",
        "version": "0.1.0",
        "description": (
            "Sentinel is a local-first multimodal AI investigation platform. "
            "API endpoints are currently in the foundation stage."
        ),
    }


# ---------------------------------------------------------------------------
# Health endpoint
# ---------------------------------------------------------------------------


@app.get("/health", tags=["Status"])
async def health() -> dict:
    """
    Health probe endpoint.

    In future, this will check:
    - PostgreSQL connectivity
    - Redis connectivity
    - Evidence storage accessibility

    For now, returns a static response indicating the API is reachable.
    """
    return {
        "status": "healthy",
        "api": "running",
        "database": "not_configured",
        "redis": "not_configured",
        "storage": "not_configured",
        "note": (
            "Database, Redis, and storage checks will be implemented "
            "once service connections are configured."
        ),
    }


# ---------------------------------------------------------------------------
# Future routers (to be registered as implementation progresses)
# ---------------------------------------------------------------------------
# from app.api import cases, evidence, analysis, timeline, graph, anomalies
#
# app.include_router(cases.router, prefix="/cases", tags=["Cases"])
# app.include_router(evidence.router, prefix="/evidence", tags=["Evidence"])
# app.include_router(analysis.router, prefix="/analysis", tags=["Analysis"])
# app.include_router(timeline.router, prefix="/timeline", tags=["Timeline"])
# app.include_router(graph.router, prefix="/graph", tags=["Graph"])
# app.include_router(anomalies.router, prefix="/anomalies", tags=["Anomalies"])
